TRUNCATE Customers;
TRUNCATE Passwords;
TRUNCATE CheckingOverdraftLogs;
TRUNCATE SavingsOverdraftLogs;
TRUNCATE CheckingTransactionHistory;
TRUNCATE SavingsTransactionHistory;
TRUNCATE TransferHistory;
TRUNCATE CryptoHistory;
TRUNCATE CryptoHoldings;